config/routes.rb
Rails.application.routes.draw do
	root "books#index"
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  PER_PAGE = 10

  def index
    page = params[:more] ? params[:more].to_i : 0

    @books = Book.limit(PER_PAGE).offset PER_PAGE * page
    p @books
    @more  = page + 1 if @books.count == PER_PAGE
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find params[:id]
  end

  def show
    @book = Book.find params[:id]
  end

  def destroy
    @book = Book.find params[:id]
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find params[:id]

    if @book.update book_params
      flash[:success] = "Updated Book"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def create
    @book = Book.new book_params

    if @book.save
      flash[:success] = "Added Book"
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :published_on, :description, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<h3>Book</h3>

<% if @book.errors.any? %>
  <div class="errors">
    <% @book.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>
<% end %>

<!-- [START multipart] -->
<%= form_for @book, :html => { :multipart => true } do |f| %>
<!-- [END multipart] -->
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :published_on, "Date Published" %>
    <%= f.date_field :published_on %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <!-- [START cover_image] -->
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <!-- [END cover_image] -->
  <button class="btn btn-success" type="submit">Save</button>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h3>Books</h3>

<%= link_to new_book_path, class: "btn btn-success btn-sm" do %>
  <i class="glyphicon glyphicon-plus"></i>
  <span>Add Book</span>
<% end %>
<% @books.each do |book| %>
  <div class="book media">
    <%= link_to book_path(book) do %>
      <div class="media-left" style="width: 100px; height: 100px">
        <%= image_tag url_for(book.image) %>
      </div>
      <div class="media-body">
        <h4><%= book.title %></h4>
        <p><%= book.author %></p>
      </div>
    <% end %>
  </div>
<% end %>

<% if @more %>
  <nav>
    <ul class="pager">
      <li><%= link_to "More", books_path(more: @more) %></li>
    </ul>
  </nav>
<% end %>

<% if @books.none? %>
  <p>No books found.</p>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h3>Book</h3>

<div class="btn-group">
  <%= link_to edit_book_path(@book), class: "btn btn-primary btn-sm" do %>
    <i class="glyphicon glyphicon-edit"></i>
    <span>Edit Book</span>
  <% end %>
  <%= link_to book_path(@book), class: "btn btn-danger btn-sm", method: :delete do %>
    <i class="glyphicon glyphicon-trash"></i>
    <span>Delete Book</span>
  <% end %>
</div>

<%# [START book_details] %>
<div class="media">
  <!-- [START cover] -->
  <div class="media-left">
    <%= image_tag @book.image %>
  </div>
  <!-- [END cover] -->
  <div class="media-body">
    <h4><%= @book.title %> | &nbsp; <small><%= @book.published_on %></small></h4>
    <h5>By <%= @book.author || "unknown" %></h5>
    <p><%= @book.description %></p>
  </div>  
</div>
<%# [END book_details] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf - Ruby on Google Cloud Platform</title>
    <meta charset="utf-8">
    <meta name="viewset" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <style type="text/css">
      img {
        width: 100px;
      }
    </style>
  </head>
  <body>
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <div class="navbar-brand">Bookshelf</div>
        </div>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="/">Books</a></li>
      </ul>
    </div>
    <div class="container">
      <% if flash.any? %>
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>"><%= message %></div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>